"""QCA_SMv0 simulator sidecar package."""

from clifford_3plus2_d5.qca_smv0.bulk_bcc import (
    BCC_ANISOTROPY_DIRECTIONS,
    BCC_DISPLACEMENTS,
    BCC_DIRAC_SPIN_DIM,
    BCC_WEYL_SPIN_DIM,
    BareBCCWalkDiagnostics,
    bare_bcc_walk_diagnostics,
    bcc_anisotropy_scaling,
    bcc_anisotropy_spread,
    bcc_axis_projectors,
    bcc_directional_phase_speeds,
    bcc_dirac_hop_completeness_residual,
    bcc_dirac_hop_matrices,
    bcc_dirac_norm_drift,
    bcc_dirac_split_symbol,
    bcc_dirac_step,
    bcc_dirac_symbol_unitarity_residual,
    bcc_hop_completeness_residual,
    bcc_hop_matrices,
    bcc_norm_drift,
    bcc_split_symbol,
    bcc_symbol_from_hops,
    bcc_symbol_unitarity_residual,
    bcc_weyl_phase_speed,
    bcc_weyl_step,
    jitted_bcc_dirac_step,
    jitted_bcc_weyl_step,
    pauli_matrices,
    small_k_dirac_speed_error,
    small_k_weyl_speed_error,
)

SIDECAR_NAME = "qca_smv0"
SIDECAR_TITLE = "QCA_SMv0"
SIDECAR_STATUS = "Stage 1 free BCC Weyl/Dirac walk implemented"

__all__ = [
    "BCC_ANISOTROPY_DIRECTIONS",
    "BCC_DISPLACEMENTS",
    "BCC_DIRAC_SPIN_DIM",
    "BCC_WEYL_SPIN_DIM",
    "SIDECAR_NAME",
    "SIDECAR_STATUS",
    "SIDECAR_TITLE",
    "BareBCCWalkDiagnostics",
    "bare_bcc_walk_diagnostics",
    "bcc_anisotropy_scaling",
    "bcc_anisotropy_spread",
    "bcc_axis_projectors",
    "bcc_directional_phase_speeds",
    "bcc_dirac_hop_completeness_residual",
    "bcc_dirac_hop_matrices",
    "bcc_dirac_norm_drift",
    "bcc_dirac_split_symbol",
    "bcc_dirac_step",
    "bcc_dirac_symbol_unitarity_residual",
    "bcc_hop_completeness_residual",
    "bcc_hop_matrices",
    "bcc_norm_drift",
    "bcc_split_symbol",
    "bcc_symbol_from_hops",
    "bcc_symbol_unitarity_residual",
    "bcc_weyl_phase_speed",
    "bcc_weyl_step",
    "jitted_bcc_dirac_step",
    "jitted_bcc_weyl_step",
    "pauli_matrices",
    "small_k_dirac_speed_error",
    "small_k_weyl_speed_error",
]
