"""One-pass finite-depth rule to bridge verdict checker."""

from __future__ import annotations

from collections import deque
from collections.abc import Sequence
from dataclasses import dataclass
from typing import Literal

import sympy as sp

from clifford_3plus2_d5.algebra.commutants import IncrementalMatrixSpan, exact_matrix_span
from clifford_3plus2_d5.algebra.matrices import commutator, identity, is_zero_matrix
from clifford_3plus2_d5.qca.gates import is_real_matrix, is_real_orthogonal
from clifford_3plus2_d5.qca.layers import QCAUpdate, layer_operator


RuleVerdict = Literal[
    "bridge_candidate",
    "falsified_no_rank_6_4_center",
    "falsified_rank_one_center",
    "candidate_only_j_not_forced",
    "not_solved",
]

EXACT_WORKING_FIELD = "exact SymPy expressions over the field generated by layer entries"


@dataclass(frozen=True)
class RuleBlochTerm:
    shift: int
    matrix: sp.Matrix


@dataclass(frozen=True)
class RuleLayerInput:
    name: str
    matrix: sp.Matrix
    support: tuple[int, ...] = (0,)
    locality_radius: int = 0
    bloch_terms: tuple[RuleBlochTerm, ...] = ()


@dataclass(frozen=True)
class CentralIdempotent:
    expression: tuple[tuple[str, sp.Expr], ...]
    matrix: sp.Matrix
    rank: int


@dataclass(frozen=True)
class ComplexStructureCandidate:
    expression: tuple[tuple[str, sp.Expr], ...]
    matrix: sp.Matrix
    source: Literal[
        "generated_algebra",
        "compatible_centralizer",
        "local_compatible_center",
    ]


@dataclass(frozen=True)
class AlgebraClosure:
    basis: tuple[sp.Matrix, ...]
    closed: bool


@dataclass(frozen=True)
class RuleToVerdictResult:
    rule_name: str
    exact_working_field: str
    natural_eigenvalue_field: str
    bloch_period: int | None
    bloch_sample_count: int
    layer_count: int
    all_layers_real_orthogonal: bool
    all_layers_local: bool
    locality_radius_bound: int
    floquet_operator: sp.Matrix
    floquet_spectrum: tuple[tuple[str, int], ...]
    generated_algebra_dimension: int
    generated_algebra_closed: bool
    center_dimension: int
    center_solved: bool
    central_idempotents: tuple[CentralIdempotent, ...]
    complementary_rank_6_4_pairs: int
    lower_rank_central_idempotents: tuple[CentralIdempotent, ...]
    generated_j_solved: bool
    generated_j_moduli_dimension: int | None
    generated_complex_structures: tuple[ComplexStructureCandidate, ...]
    compatible_centralizer_dimension: int
    compatible_j_solved: bool
    compatible_j_moduli_dimension: int | None
    compatible_complex_structures: tuple[ComplexStructureCandidate, ...]
    local_compatible_operator_dimension: int
    local_compatible_j_solved: bool
    local_compatible_j_moduli_dimension: int | None
    local_compatible_complex_structures: tuple[ComplexStructureCandidate, ...]
    forced_j_found: bool
    rank_6_4_pair_commutes_with_forced_j: bool
    pass_rule_to_bridge: bool
    verdict: RuleVerdict
    load_bearing_qca_bridge: bool = False


def _flatten(matrix: sp.Matrix) -> sp.Matrix:
    return sp.Matrix(matrix.rows * matrix.cols, 1, list(matrix))


def _matrix_from_flat(vector: sp.Matrix, dimension: int) -> sp.Matrix:
    return sp.Matrix(dimension, dimension, list(vector))


def _validate_layers(layers: Sequence[RuleLayerInput], *, dimension: int) -> None:
    if not layers:
        raise ValueError("at least one rule layer is required")
    for layer in layers:
        if layer.matrix.shape != (dimension, dimension):
            msg = f"layer {layer.name!r} is not {dimension}x{dimension}"
            raise ValueError(msg)
        for term in layer.bloch_terms:
            if term.matrix.shape != (dimension, dimension):
                msg = f"Bloch term in layer {layer.name!r} is not {dimension}x{dimension}"
                raise ValueError(msg)


def _layer_is_local(layer: RuleLayerInput) -> bool:
    if not layer.support or any(site < 0 for site in layer.support):
        return False
    return layer.locality_radius >= max(layer.support) - min(layer.support)


def _locality_radius_bound(layers: Sequence[RuleLayerInput]) -> int:
    return max((layer.locality_radius for layer in layers), default=0)


def floquet_operator(layers: Sequence[RuleLayerInput], *, dimension: int = 10) -> sp.Matrix:
    result = identity(dimension)
    for layer in layers:
        result = layer.matrix * result
    return result


def _root_of_unity(period: int, sample: int) -> sp.Expr:
    angle = 2 * sp.pi * sp.Rational(sample, period)
    return sp.simplify(sp.cos(angle) + sp.I * sp.sin(angle))


def _bloch_layer_symbol_at_root(
    layer: RuleLayerInput,
    *,
    period: int,
    sample: int,
) -> sp.Matrix:
    if not layer.bloch_terms:
        return layer.matrix
    zeta = _root_of_unity(period, sample)
    symbol = sp.zeros(layer.matrix.rows)
    for term in layer.bloch_terms:
        symbol += term.matrix * sp.expand(zeta**term.shift)
    return symbol.applyfunc(sp.expand)


def bloch_floquet_operators(
    layers: Sequence[RuleLayerInput],
    *,
    bloch_period: int,
    dimension: int = 10,
) -> tuple[sp.Matrix, ...]:
    samples = []
    for sample in range(bloch_period):
        result = identity(dimension)
        for layer in layers:
            result = _bloch_layer_symbol_at_root(layer, period=bloch_period, sample=sample) * result
        samples.append(result.applyfunc(sp.expand))
    return tuple(samples)


def _terms_by_shift(terms: Sequence[RuleBlochTerm]) -> dict[int, sp.Matrix]:
    by_shift: dict[int, sp.Matrix] = {}
    for term in terms:
        by_shift[term.shift] = by_shift.get(term.shift, sp.zeros(term.matrix.rows)) + term.matrix
    return by_shift


def _bloch_layer_laurent_orthogonal(layer: RuleLayerInput, *, dimension: int) -> bool:
    if not layer.bloch_terms:
        return is_real_matrix(layer.matrix) and is_real_orthogonal(layer.matrix)
    terms_by_shift = _terms_by_shift(layer.bloch_terms)
    deltas = {left - right for left in terms_by_shift for right in terms_by_shift}
    one = identity(dimension)
    zero = sp.zeros(dimension)
    for delta in deltas:
        right_sum = sp.zeros(dimension)
        left_sum = sp.zeros(dimension)
        for shift, matrix in terms_by_shift.items():
            shifted = terms_by_shift.get(shift + delta)
            if shifted is None:
                continue
            right_sum += matrix.T * shifted
            left_sum += matrix * shifted.T
        expected = one if delta == 0 else zero
        if sp.simplify(right_sum - expected) != zero:
            return False
        if sp.simplify(left_sum - expected) != zero:
            return False
    return True


def generated_algebra_closure(
    generators: Sequence[sp.Matrix],
    *,
    dimension: int = 10,
    max_dimension: int | None = None,
) -> AlgebraClosure:
    limit = max_dimension if max_dimension is not None else dimension * dimension
    if limit <= 0:
        raise ValueError("max_dimension must be positive")

    span = exact_matrix_span(
        (identity(dimension), *generators),
        rows=dimension,
        cols=dimension,
        add_matrices=False,
    )
    basis: list[sp.Matrix] = []
    queue: deque[sp.Matrix] = deque()

    def add_to_basis(matrix: sp.Matrix, *, enqueue: bool) -> bool:
        nonlocal span
        try:
            added = span.add(matrix)
        except ValueError:
            fallback = IncrementalMatrixSpan(rows=dimension, cols=dimension)
            for basis_matrix in basis:
                fallback.add(basis_matrix)
            span = fallback
            added = span.add(matrix)
        if not added:
            return False
        basis.append(matrix)
        if enqueue:
            queue.append(matrix)
        return True

    add_to_basis(identity(dimension), enqueue=False)
    for matrix in generators:
        add_to_basis(matrix, enqueue=True)
        if len(basis) >= limit:
            return AlgebraClosure(
                basis=tuple(basis),
                closed=len(basis) == dimension * dimension,
            )

    while queue and len(basis) < dimension * dimension:
        matrix = queue.popleft()
        for generator in generators:
            add_to_basis(matrix * generator, enqueue=True)
            if len(basis) == dimension * dimension:
                return AlgebraClosure(basis=tuple(basis), closed=True)
            if len(basis) >= limit:
                return AlgebraClosure(basis=tuple(basis), closed=False)
    return AlgebraClosure(basis=tuple(basis), closed=True)


def _center_basis_from_commutators(
    algebra_basis: Sequence[sp.Matrix],
    *,
    dimension: int,
) -> tuple[sp.Matrix, ...]:
    variables = sp.symbols(f"z0:{len(algebra_basis)}")
    candidate = sp.zeros(dimension)
    for variable, basis_matrix in zip(variables, algebra_basis, strict=True):
        candidate += variable * basis_matrix

    equations = [
        value for basis_matrix in algebra_basis for value in commutator(candidate, basis_matrix)
    ]
    coefficient_matrix, _ = sp.linear_eq_to_matrix(equations, variables)
    center = []
    for vector in coefficient_matrix.nullspace():
        matrix = sp.zeros(dimension)
        for coefficient, basis_matrix in zip(vector, algebra_basis, strict=True):
            matrix += coefficient * basis_matrix
        center.append(matrix)
    return tuple(center)


def _center_basis_from_structure_constants(
    algebra_basis: Sequence[sp.Matrix],
    *,
    dimension: int,
) -> tuple[sp.Matrix, ...] | None:
    coordinate_system = exact_matrix_span(algebra_basis)
    if coordinate_system.rank != len(algebra_basis):
        raise ValueError("algebra_basis must be linearly independent")

    basis_size = len(algebra_basis)
    variables = sp.symbols(f"z0:{basis_size}")
    equations = []
    product_coordinates: dict[tuple[int, int], tuple[sp.Expr, ...]] = {}
    for left_index, left in enumerate(algebra_basis):
        for right_index, right in enumerate(algebra_basis):
            try:
                coordinates = coordinate_system.coordinates(left * right)
            except ValueError:
                return None
            if coordinates is None:
                return None
            product_coordinates[(left_index, right_index)] = coordinates

    for basis_index in range(basis_size):
        for coordinate_index in range(basis_size):
            equations.append(
                sp.expand(
                    sum(
                        variables[left_index]
                        * (
                            product_coordinates[(left_index, basis_index)][coordinate_index]
                            - product_coordinates[(basis_index, left_index)][coordinate_index]
                        )
                        for left_index in range(basis_size)
                    )
                )
            )

    coefficient_matrix, _ = sp.linear_eq_to_matrix(equations, variables)
    center = []
    for vector in coefficient_matrix.nullspace():
        matrix = sp.zeros(dimension)
        for coefficient, basis_matrix in zip(vector, algebra_basis, strict=True):
            matrix += coefficient * basis_matrix
        center.append(matrix)
    return tuple(center)


def generated_algebra_basis(
    generators: Sequence[sp.Matrix],
    *,
    dimension: int = 10,
) -> tuple[sp.Matrix, ...]:
    return generated_algebra_closure(generators, dimension=dimension).basis


def center_basis_of_algebra(
    algebra_basis: Sequence[sp.Matrix],
    *,
    dimension: int = 10,
) -> tuple[sp.Matrix, ...]:
    center = _center_basis_from_structure_constants(algebra_basis, dimension=dimension)
    if center is not None:
        return center
    return _center_basis_from_commutators(algebra_basis, dimension=dimension)


def centralizer_basis(
    generators: Sequence[sp.Matrix],
    *,
    dimension: int = 10,
) -> tuple[sp.Matrix, ...]:
    variables = sp.symbols(f"x0:{dimension * dimension}")
    candidate = sp.Matrix(dimension, dimension, variables)
    equations = [value for generator in generators for value in commutator(candidate, generator)]
    coefficient_matrix, _ = sp.linear_eq_to_matrix(equations, variables)
    return tuple(_matrix_from_flat(vector, dimension) for vector in coefficient_matrix.nullspace())


def _basis_expression(
    coefficients: Sequence[sp.Expr],
    prefix: str,
) -> tuple[tuple[str, sp.Expr], ...]:
    return tuple(
        (f"{prefix}_{index}", coefficient)
        for index, coefficient in enumerate(coefficients)
        if coefficient != 0
    )


def _solve_matrix_equations(
    basis: Sequence[sp.Matrix],
    matrix_equation: sp.Matrix,
    *,
    variables: Sequence[sp.Symbol],
) -> tuple[dict[sp.Symbol, sp.Expr], ...]:
    equations = tuple(sp.expand(value) for value in matrix_equation if sp.expand(value) != 0)
    if not equations:
        return ({variable: sp.Integer(0) for variable in variables},)
    solutions = sp.solve(equations, tuple(variables), dict=True)
    complete_solutions = []
    for solution in solutions:
        if all(variable in solution for variable in variables):
            complete_solutions.append(solution)
    return tuple(complete_solutions)


def _polynomial_system_moduli_dimension(
    equations: Sequence[sp.Expr],
    variables: Sequence[sp.Symbol],
) -> int | None:
    if not equations:
        return len(variables)
    try:
        basis = sp.groebner(equations, *variables)
    except (NotImplementedError, ValueError, sp.PolynomialError):
        return None
    if basis.is_zero_dimensional:
        return 0
    return None


def _natural_eigenvalue_field_label(eigenvalues: Sequence[sp.Expr]) -> str:
    if all(value.is_Rational for value in eigenvalues):
        return "QQ"
    values = ", ".join(str(value) for value in eigenvalues)
    return f"QQ({values})"


def _compatible_j_moduli_dimension_from_single_generator(
    generator: sp.Matrix,
) -> int | None:
    """HEURISTIC: estimate compatible-J moduli for one semisimple generator.

    This spectral orbit count is only correct for a single semisimple
    generator with all non-real eigenvalues paired by complex conjugation.
    Multi-layer rules and non-semisimple cases must report ``None`` unless the
    polynomial solve computes a dimension directly.
    """

    eigenvals = generator.eigenvals()
    seen: set[sp.Expr] = set()
    dimension = 0
    for eigenvalue, multiplicity in eigenvals.items():
        if eigenvalue in seen:
            continue
        conjugate = sp.conjugate(eigenvalue)
        seen.add(eigenvalue)
        seen.add(conjugate)

        if sp.simplify(eigenvalue - conjugate) == 0:
            if multiplicity % 2:
                return None
            half_rank = multiplicity // 2
            dimension += half_rank * (half_rank - 1)
            continue

        conjugate_multiplicity = eigenvals.get(conjugate)
        if conjugate_multiplicity != multiplicity:
            return None
        if multiplicity > 1:
            dimension += multiplicity * (multiplicity + 1) // 2
    return dimension


def solve_central_idempotents(
    center_basis: Sequence[sp.Matrix],
    *,
    max_center_dimension: int = 8,
    dimension: int = 10,
) -> tuple[bool, tuple[CentralIdempotent, ...]]:
    if len(center_basis) > max_center_dimension:
        return False, ()

    variables = sp.symbols(f"c0:{len(center_basis)}")
    candidate = sp.zeros(dimension)
    for variable, basis_matrix in zip(variables, center_basis, strict=True):
        candidate += variable * basis_matrix

    solutions = _solve_matrix_equations(
        center_basis,
        candidate * candidate - candidate,
        variables=variables,
    )
    idempotents: list[CentralIdempotent] = []
    seen: set[tuple[sp.Expr, ...]] = set()
    for solution in solutions:
        coefficients = tuple(sp.simplify(solution[variable]) for variable in variables)
        matrix = sp.zeros(dimension)
        for coefficient, basis_matrix in zip(coefficients, center_basis, strict=True):
            matrix += coefficient * basis_matrix
        if not is_real_matrix(matrix):
            continue
        key = tuple(sp.simplify(value) for value in matrix)
        if key in seen:
            continue
        seen.add(key)
        idempotents.append(
            CentralIdempotent(
                expression=_basis_expression(coefficients, "center"),
                matrix=matrix,
                rank=matrix.rank(),
            )
        )
    return True, tuple(sorted(idempotents, key=lambda item: (item.rank, str(item.expression))))


def solve_complex_structures_in_basis(
    basis: Sequence[sp.Matrix],
    *,
    source: Literal[
        "generated_algebra",
        "compatible_centralizer",
        "local_compatible_center",
    ],
    max_basis_dimension: int = 8,
    dimension: int = 10,
) -> tuple[bool, int | None, tuple[ComplexStructureCandidate, ...]]:
    if len(basis) > max_basis_dimension:
        return False, None, ()

    variables = sp.symbols(f"j0:{len(basis)}")
    candidate = sp.zeros(dimension)
    for variable, basis_matrix in zip(variables, basis, strict=True):
        candidate += variable * basis_matrix

    equations = (candidate * candidate + identity(dimension)).col_join(
        candidate.T * candidate - identity(dimension)
    )
    expanded_equations = tuple(sp.expand(value) for value in equations if sp.expand(value) != 0)
    moduli_dimension = _polynomial_system_moduli_dimension(expanded_equations, variables)
    solutions = _solve_matrix_equations(basis, equations, variables=variables)
    candidates: list[ComplexStructureCandidate] = []
    seen: set[tuple[sp.Expr, ...]] = set()
    for solution in solutions:
        coefficients = tuple(sp.simplify(solution[variable]) for variable in variables)
        matrix = sp.zeros(dimension)
        for coefficient, basis_matrix in zip(coefficients, basis, strict=True):
            matrix += coefficient * basis_matrix
        if not is_real_matrix(matrix):
            continue
        key = tuple(sp.simplify(value) for value in matrix)
        if key in seen:
            continue
        seen.add(key)
        candidates.append(
            ComplexStructureCandidate(
                expression=_basis_expression(coefficients, source),
                matrix=matrix,
                source=source,
            )
        )
    return True, moduli_dimension, tuple(candidates)


def _independent_block_basis(
    basis: Sequence[sp.Matrix],
    projector: sp.Matrix,
) -> tuple[sp.Matrix, ...]:
    span = IncrementalMatrixSpan(rows=projector.rows, cols=projector.cols)
    span.add(projector)
    block_basis = [projector]
    for basis_matrix in basis:
        candidate = (projector * basis_matrix).applyfunc(sp.simplify)
        if span.add(candidate):
            block_basis.append(candidate)
    return tuple(block_basis)


def solve_complex_structures_from_idempotent_splitting(
    basis: Sequence[sp.Matrix],
    idempotents: Sequence[CentralIdempotent],
    *,
    source: Literal[
        "generated_algebra",
        "compatible_centralizer",
        "local_compatible_center",
    ],
    dimension: int = 10,
) -> tuple[bool, int | None, tuple[ComplexStructureCandidate, ...]]:
    """Solve finite ``J`` choices from a two-block real center splitting.

    This is the bounded Path-A path for algebras with complementary central
    idempotents ``P`` and ``I-P``. A one-dimensional projected summand has no
    real solution to ``J^2 = -P`` and is reported as a solved zero-candidate
    case. A two-dimensional projected summand is solved analytically: if
    ``x^2 = a P + b x``, then ``u P + v x`` squares to ``-P`` exactly when
    ``u = -b v / 2`` and ``v^2 = -1 / (a + b^2/4)``. Richer summands require a
    different solver and are reported as unsupported.
    """

    nontrivial_pairs = []
    one = identity(dimension)
    zero = sp.zeros(dimension)
    matrix_zero = sp.zeros(dimension)

    def same_matrix(left: sp.Matrix, right: sp.Matrix) -> bool:
        return (left - right).applyfunc(sp.simplify) == matrix_zero

    for left_index, left in enumerate(idempotents):
        if left.rank in (0, dimension):
            continue
        for right_index, right in enumerate(idempotents):
            if right_index <= left_index:
                continue
            if right.rank in (0, dimension) or left.rank + right.rank != dimension:
                continue
            if (
                same_matrix(left.matrix + right.matrix, one)
                and same_matrix(left.matrix * right.matrix, zero)
                and same_matrix(right.matrix * left.matrix, zero)
            ):
                nontrivial_pairs.append((left.matrix, right.matrix))
    if not nontrivial_pairs:
        return False, None, ()

    coordinate_system = IncrementalMatrixSpan(rows=dimension, cols=dimension)
    for basis_matrix in basis:
        if not coordinate_system.add(basis_matrix):
            raise ValueError("basis must be linearly independent")

    def block_solutions(projector: sp.Matrix) -> tuple[sp.Matrix, ...] | None:
        block_basis = _independent_block_basis(basis, projector)
        if len(block_basis) != 2:
            return None
        block_span = IncrementalMatrixSpan(rows=dimension, cols=dimension)
        for basis_matrix in block_basis:
            if not block_span.add(basis_matrix):
                raise ValueError("block_basis must be linearly independent")
        coordinates = block_span.coordinates(
            (block_basis[1] * block_basis[1]).applyfunc(sp.simplify)
        )
        if coordinates is None:
            return None
        a, b = (sp.simplify(item) for item in coordinates)
        denominator = sp.simplify(a + b**2 / 4)
        if denominator == 0:
            return None
        v = sp.sqrt(sp.simplify(-1 / denominator))
        u = sp.simplify(-b * v / 2)
        positive = (u * projector + v * block_basis[1]).applyfunc(sp.simplify)
        negative = (-positive).applyfunc(sp.simplify)
        return (positive, negative)

    candidates: list[ComplexStructureCandidate] = []
    seen: set[tuple[sp.Expr, ...]] = set()
    unsupported_pair_seen = False
    for left_projector, right_projector in nontrivial_pairs:
        left_block_basis = _independent_block_basis(basis, left_projector)
        right_block_basis = _independent_block_basis(basis, right_projector)
        if len(left_block_basis) == 1 or len(right_block_basis) == 1:
            continue
        if len(left_block_basis) != 2 or len(right_block_basis) != 2:
            unsupported_pair_seen = True
            continue

        left_solutions = block_solutions(left_projector)
        right_solutions = block_solutions(right_projector)
        if left_solutions is None or right_solutions is None:
            unsupported_pair_seen = True
            continue
        for left_j in left_solutions:
            for right_j in right_solutions:
                matrix = (left_j + right_j).applyfunc(sp.simplify)
                if not is_real_matrix(matrix):
                    continue
                if (matrix * matrix + one).applyfunc(sp.simplify) != zero:
                    continue
                if (matrix.T * matrix - one).applyfunc(sp.simplify) != zero:
                    continue
                coordinates = coordinate_system.coordinates(matrix)
                if coordinates is None:
                    continue
                key = tuple(sp.simplify(value) for value in matrix)
                if key in seen:
                    continue
                seen.add(key)
                candidates.append(
                    ComplexStructureCandidate(
                        expression=_basis_expression(coordinates, source),
                        matrix=matrix,
                        source=source,
                    )
                )
    if unsupported_pair_seen and not candidates:
        return False, None, ()
    return True, 0, tuple(candidates)


def _complementary_rank_6_4_pairs(
    idempotents: Sequence[CentralIdempotent],
    *,
    dimension: int = 10,
) -> tuple[tuple[CentralIdempotent, CentralIdempotent], ...]:
    pairs = []
    for rank_6 in (item for item in idempotents if item.rank == 6):
        for rank_4 in (item for item in idempotents if item.rank == 4):
            if (
                rank_6.matrix + rank_4.matrix == identity(dimension)
                and rank_6.matrix * rank_4.matrix == sp.zeros(dimension)
                and rank_4.matrix * rank_6.matrix == sp.zeros(dimension)
            ):
                pairs.append((rank_6, rank_4))
    return tuple(pairs)


def _lower_rank_idempotents_inside_pairs(
    idempotents: Sequence[CentralIdempotent],
    pairs: Sequence[tuple[CentralIdempotent, CentralIdempotent]],
) -> tuple[CentralIdempotent, ...]:
    bad: list[CentralIdempotent] = []
    seen: set[tuple[sp.Expr, ...]] = set()
    for candidate in idempotents:
        if candidate.rank == 0 or candidate.rank == 10:
            continue
        if candidate.rank < 4:
            key = tuple(candidate.matrix)
            if key not in seen:
                seen.add(key)
                bad.append(candidate)
            continue
        if candidate.rank == 6:
            continue
        for rank_6, rank_4 in pairs:
            if candidate.matrix == rank_6.matrix or candidate.matrix == rank_4.matrix:
                continue
            inside_rank_6 = candidate.matrix * rank_6.matrix == candidate.matrix
            inside_rank_4 = candidate.matrix * rank_4.matrix == candidate.matrix
            if inside_rank_6 or inside_rank_4:
                key = tuple(candidate.matrix)
                if key not in seen:
                    seen.add(key)
                    bad.append(candidate)
    return tuple(bad)


def _forced_j(
    generated: Sequence[ComplexStructureCandidate],
    compatible: Sequence[ComplexStructureCandidate],
    *,
    compatible_solved: bool,
    compatible_j_moduli_dimension: int | None,
) -> bool:
    # Candidate counting is meaningful only after the compatible variety is
    # certified zero-dimensional.
    if (
        not generated
        or not compatible_solved
        or compatible_j_moduli_dimension != 0
        or len(compatible) != 2
    ):
        return False
    for candidate in generated:
        candidate_pair = (candidate.matrix, -candidate.matrix)
        if all(any(option == item.matrix for option in candidate_pair) for item in compatible):
            return True
    return False


def _pair_commutes_with_forced_j(
    pairs: Sequence[tuple[CentralIdempotent, CentralIdempotent]],
    generated: Sequence[ComplexStructureCandidate],
    *,
    forced_j_found: bool,
) -> bool:
    if not forced_j_found:
        return False
    return any(
        is_zero_matrix(commutator(j_candidate.matrix, rank_6.matrix))
        and is_zero_matrix(commutator(j_candidate.matrix, rank_4.matrix))
        for rank_6, rank_4 in pairs
        for j_candidate in generated
    )


def rule_to_verdict(
    layers: Sequence[RuleLayerInput],
    *,
    rule_name: str = "anonymous_rule",
    max_center_solve_dimension: int = 8,
    max_j_solve_dimension: int = 8,
    max_generated_algebra_dimension: int | None = None,
    bloch_period: int | None = None,
    dimension: int = 10,
) -> RuleToVerdictResult:
    _validate_layers(layers, dimension=dimension)
    if bloch_period is not None and bloch_period <= 0:
        raise ValueError("bloch_period must be positive")
    if bloch_period is None:
        floquet_samples = (floquet_operator(layers, dimension=dimension),)
        algebra_generators = tuple(layer.matrix for layer in layers)
        natural_eigenvalue_field = _natural_eigenvalue_field_label(
            floquet_samples[0].eigenvals().keys()
        )
        bloch_sample_count = 0
        layers_are_real_orthogonal = all(
            is_real_matrix(layer.matrix) and is_real_orthogonal(layer.matrix) for layer in layers
        )
    else:
        floquet_samples = bloch_floquet_operators(
            layers,
            bloch_period=bloch_period,
            dimension=dimension,
        )
        algebra_generators = floquet_samples
        natural_eigenvalue_field = f"QQ(zeta_{bloch_period})"
        bloch_sample_count = len(floquet_samples)
        layers_are_real_orthogonal = all(
            all(is_real_matrix(term.matrix) for term in layer.bloch_terms)
            and _bloch_layer_laurent_orthogonal(layer, dimension=dimension)
            for layer in layers
        )
    layers_are_local = all(_layer_is_local(layer) for layer in layers)
    locality_radius_bound = _locality_radius_bound(layers)
    floquet = floquet_samples[0]
    algebra_closure = generated_algebra_closure(
        algebra_generators,
        dimension=dimension,
        max_dimension=max_generated_algebra_dimension,
    )
    algebra = algebra_closure.basis
    if not algebra_closure.closed:
        return RuleToVerdictResult(
            rule_name=rule_name,
            exact_working_field=EXACT_WORKING_FIELD,
            natural_eigenvalue_field=natural_eigenvalue_field,
            bloch_period=bloch_period,
            bloch_sample_count=bloch_sample_count,
            layer_count=len(layers),
            all_layers_real_orthogonal=layers_are_real_orthogonal,
            all_layers_local=layers_are_local,
            locality_radius_bound=locality_radius_bound,
            floquet_operator=floquet,
            floquet_spectrum=tuple(
                sorted(
                    (str(value), multiplicity)
                    for value, multiplicity in floquet.eigenvals().items()
                )
            ),
            generated_algebra_dimension=len(algebra),
            generated_algebra_closed=False,
            center_dimension=0,
            center_solved=False,
            central_idempotents=(),
            complementary_rank_6_4_pairs=0,
            lower_rank_central_idempotents=(),
            generated_j_solved=False,
            generated_j_moduli_dimension=None,
            generated_complex_structures=(),
            compatible_centralizer_dimension=0,
            compatible_j_solved=False,
            compatible_j_moduli_dimension=None,
            compatible_complex_structures=(),
            local_compatible_operator_dimension=0,
            local_compatible_j_solved=False,
            local_compatible_j_moduli_dimension=None,
            local_compatible_complex_structures=(),
            forced_j_found=False,
            rank_6_4_pair_commutes_with_forced_j=False,
            pass_rule_to_bridge=False,
            verdict="not_solved",
        )

    center = center_basis_of_algebra(algebra, dimension=dimension)
    center_solved, idempotents = solve_central_idempotents(
        center,
        max_center_dimension=max_center_solve_dimension,
        dimension=dimension,
    )
    rank_pairs = _complementary_rank_6_4_pairs(idempotents, dimension=dimension)
    lower_rank = _lower_rank_idempotents_inside_pairs(idempotents, rank_pairs)

    generated_j_solved, generated_j_moduli_dimension, generated_j = (
        solve_complex_structures_in_basis(
            algebra,
            source="generated_algebra",
            max_basis_dimension=max_j_solve_dimension,
            dimension=dimension,
        )
    )
    compatible_basis = centralizer_basis(algebra_generators, dimension=dimension)
    (
        compatible_j_solved,
        solved_compatible_j_moduli_dimension,
        compatible_j,
    ) = solve_complex_structures_in_basis(
        compatible_basis,
        source="compatible_centralizer",
        max_basis_dimension=max_j_solve_dimension,
        dimension=dimension,
    )
    if bloch_period is not None and rank_pairs and not compatible_j_solved:
        (
            compatible_j_solved,
            solved_compatible_j_moduli_dimension,
            compatible_j,
        ) = solve_complex_structures_from_idempotent_splitting(
            compatible_basis,
            idempotents,
            source="compatible_centralizer",
            dimension=dimension,
        )
    estimated_compatible_j_moduli_dimension = (
        _compatible_j_moduli_dimension_from_single_generator(algebra_generators[0])
        if bloch_period is None and len(algebra_generators) == 1
        else None
    )
    compatible_j_moduli_dimension = (
        solved_compatible_j_moduli_dimension
        if solved_compatible_j_moduli_dimension is not None
        else estimated_compatible_j_moduli_dimension
    )
    # This is intentionally not "all local on-site operators." For a radius-0
    # one-cell rule, all on-site local operators would be M_10(R). The
    # falsifier used here is narrower: solve J inside the rule-generated local
    # center. If that subalgebra already produces multiple J choices, the rule
    # has not singled out one.
    local_compatible_basis = center
    (
        local_compatible_j_solved,
        local_compatible_j_moduli_dimension,
        local_compatible_j,
    ) = solve_complex_structures_in_basis(
        local_compatible_basis,
        source="local_compatible_center",
        max_basis_dimension=max_j_solve_dimension,
        dimension=dimension,
    )
    if bloch_period is not None and rank_pairs and not local_compatible_j_solved:
        (
            local_compatible_j_solved,
            local_compatible_j_moduli_dimension,
            local_compatible_j,
        ) = solve_complex_structures_from_idempotent_splitting(
            local_compatible_basis,
            idempotents,
            source="local_compatible_center",
            dimension=dimension,
        )
    forced_j_found = _forced_j(
        generated_j,
        local_compatible_j,
        compatible_solved=local_compatible_j_solved,
        compatible_j_moduli_dimension=local_compatible_j_moduli_dimension,
    )
    pair_commutes = _pair_commutes_with_forced_j(
        rank_pairs,
        generated_j,
        forced_j_found=forced_j_found,
    )
    pass_rule = bool(
        layers_are_real_orthogonal
        and layers_are_local
        and center_solved
        and generated_j_solved
        and local_compatible_j_solved
        and rank_pairs
        and not lower_rank
        and forced_j_found
        and pair_commutes
    )

    if pass_rule:
        verdict: RuleVerdict = "bridge_candidate"
    elif not center_solved or not generated_j_solved:
        verdict = "not_solved"
    elif lower_rank:
        verdict = "falsified_rank_one_center"
    elif not rank_pairs:
        verdict = "falsified_no_rank_6_4_center"
    else:
        verdict = "candidate_only_j_not_forced"

    return RuleToVerdictResult(
        rule_name=rule_name,
        exact_working_field=EXACT_WORKING_FIELD,
        natural_eigenvalue_field=natural_eigenvalue_field,
        bloch_period=bloch_period,
        bloch_sample_count=bloch_sample_count,
        layer_count=len(layers),
        all_layers_real_orthogonal=layers_are_real_orthogonal,
        all_layers_local=layers_are_local,
        locality_radius_bound=locality_radius_bound,
        floquet_operator=floquet,
        floquet_spectrum=tuple(
            sorted(
                (str(value), multiplicity) for value, multiplicity in floquet.eigenvals().items()
            )
        ),
        generated_algebra_dimension=len(algebra),
        generated_algebra_closed=True,
        center_dimension=len(center),
        center_solved=center_solved,
        central_idempotents=idempotents,
        complementary_rank_6_4_pairs=len(rank_pairs),
        lower_rank_central_idempotents=lower_rank,
        generated_j_solved=generated_j_solved,
        generated_j_moduli_dimension=generated_j_moduli_dimension,
        generated_complex_structures=generated_j,
        compatible_centralizer_dimension=len(compatible_basis),
        compatible_j_solved=compatible_j_solved,
        compatible_j_moduli_dimension=compatible_j_moduli_dimension,
        compatible_complex_structures=compatible_j,
        local_compatible_operator_dimension=len(local_compatible_basis),
        local_compatible_j_solved=local_compatible_j_solved,
        local_compatible_j_moduli_dimension=local_compatible_j_moduli_dimension,
        local_compatible_complex_structures=local_compatible_j,
        forced_j_found=forced_j_found,
        rank_6_4_pair_commutes_with_forced_j=pair_commutes,
        pass_rule_to_bridge=pass_rule,
        verdict=verdict,
    )


def layers_from_update(update: QCAUpdate) -> tuple[RuleLayerInput, ...]:
    return tuple(
        RuleLayerInput(
            name=layer.name,
            matrix=layer_operator(layer),
            support=tuple(site for gate in layer.gates for site in gate.support) or (0,),
            locality_radius=max((gate.locality_radius for gate in layer.gates), default=0),
        )
        for layer in update.layers
    )


def rule_to_verdict_from_update(update: QCAUpdate) -> RuleToVerdictResult:
    return rule_to_verdict(layers_from_update(update), rule_name=update.name)


def _idempotent_to_dict(idempotent: CentralIdempotent) -> dict[str, object]:
    return {
        "expression": [
            {"basis": name, "coefficient": str(coefficient)}
            for name, coefficient in idempotent.expression
        ],
        "rank": idempotent.rank,
    }


def _complex_structure_to_dict(candidate: ComplexStructureCandidate) -> dict[str, object]:
    return {
        "expression": [
            {"basis": name, "coefficient": str(coefficient)}
            for name, coefficient in candidate.expression
        ],
        "source": candidate.source,
    }


def result_to_dict(result: RuleToVerdictResult) -> dict[str, object]:
    return {
        "rule_name": result.rule_name,
        "exact_working_field": result.exact_working_field,
        "natural_eigenvalue_field": result.natural_eigenvalue_field,
        "bloch_period": result.bloch_period,
        "bloch_sample_count": result.bloch_sample_count,
        "layer_count": result.layer_count,
        "all_layers_real_orthogonal": result.all_layers_real_orthogonal,
        "all_layers_local": result.all_layers_local,
        "locality_radius_bound": result.locality_radius_bound,
        "floquet_spectrum": [
            {"eigenvalue": value, "multiplicity": multiplicity}
            for value, multiplicity in result.floquet_spectrum
        ],
        "generated_algebra_dimension": result.generated_algebra_dimension,
        "generated_algebra_closed": result.generated_algebra_closed,
        "center_dimension": result.center_dimension,
        "center_solved": result.center_solved,
        "central_idempotents": [
            _idempotent_to_dict(idempotent) for idempotent in result.central_idempotents
        ],
        "central_idempotent_ranks": [idempotent.rank for idempotent in result.central_idempotents],
        "complementary_rank_6_4_pairs": result.complementary_rank_6_4_pairs,
        "lower_rank_central_idempotents": [
            _idempotent_to_dict(idempotent) for idempotent in result.lower_rank_central_idempotents
        ],
        "generated_j_solved": result.generated_j_solved,
        "generated_j_moduli_dimension": result.generated_j_moduli_dimension,
        "generated_complex_structures": [
            _complex_structure_to_dict(candidate)
            for candidate in result.generated_complex_structures
        ],
        "compatible_j_solved": result.compatible_j_solved,
        "compatible_centralizer_dimension": result.compatible_centralizer_dimension,
        "compatible_j_moduli_dimension": result.compatible_j_moduli_dimension,
        "compatible_complex_structure_count": len(result.compatible_complex_structures),
        "compatible_complex_structures": [
            _complex_structure_to_dict(candidate)
            for candidate in result.compatible_complex_structures
        ],
        "local_compatible_operator_dimension": result.local_compatible_operator_dimension,
        "local_compatible_j_solved": result.local_compatible_j_solved,
        "local_compatible_j_moduli_dimension": result.local_compatible_j_moduli_dimension,
        "local_compatible_complex_structure_count": (
            len(result.local_compatible_complex_structures)
        ),
        "local_compatible_complex_structures": [
            _complex_structure_to_dict(candidate)
            for candidate in result.local_compatible_complex_structures
        ],
        "forced_j_found": result.forced_j_found,
        "rank_6_4_pair_commutes_with_forced_j": (result.rank_6_4_pair_commutes_with_forced_j),
        "pass_rule_to_bridge": result.pass_rule_to_bridge,
        "verdict": result.verdict,
        "load_bearing_qca_bridge": result.load_bearing_qca_bridge,
    }
