"""Lab A same-spectrum wall candidates."""

from __future__ import annotations

from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from itertools import product

import sympy as sp

from clifford_3plus2_d5.lepton.primitives import (
    LAB_A_DIMENSION,
    LabACandidate,
    lab_a_primitive_layers,
)
from clifford_3plus2_d5.lepton.wall import (
    LocalityConstraint,
    LocalityModel,
    solve_t_intertwiner_orthogonal,
    spectrum_matches,
)
from clifford_3plus2_d5.obstruction_r10.qca.rule_verdict import RuleLayerInput


@dataclass(frozen=True)
class LabAWallCandidate(LabACandidate):
    """A same-spectrum Lab A wall candidate with a tiered transition witness."""

    left_name: str = ""
    right_name: str = ""
    transition_tier: str = "no_solutions"
    transition_index: int = 0

    @property
    def metadata(self) -> tuple[tuple[str, str], ...]:
        return (
            ("left", self.left_name),
            ("right", self.right_name),
            ("transition_tier", self.transition_tier),
            ("transition_index", str(self.transition_index)),
        )


def lab_a_wall_locality_constraint() -> LocalityConstraint:
    """Return the first Lab A wall locality model.

    Session 4 uses a single-site internal transition model for R^4, so the
    block mask intentionally allows the full internal carrier. The tiered
    intertwiner source is still recorded on each candidate.
    """

    return LocalityConstraint(
        model=LocalityModel.BLOCK_SUPPORT,
        blocks=((0, LAB_A_DIMENSION),),
        allowed_block_pairs=((0, 0),),
    )


def _transition_layer(
    *,
    name: str,
    matrix: sp.Matrix,
) -> RuleLayerInput:
    return RuleLayerInput(name=name, matrix=matrix, support=(0,), locality_radius=0)


def iter_lab_a_wall_candidates(
    *,
    angle_orders: Sequence[int] = (2, 3, 4),
    max_pairs: int | None = None,
    max_transitions_per_pair: int = 2,
    max_candidates: int | None = None,
    include_generic: bool = False,
) -> Iterable[LabAWallCandidate]:
    """Yield bounded same-spectrum wall candidates for Lab A.

    The candidate algebra is generated by ``U_left``, ``U_right``, and one
    orthogonal transition ``T`` satisfying ``T U_left = U_right T``.
    Generic symbolic intertwiners are disabled by default to keep Session 4
    scans deterministic and cheap.
    """

    if max_transitions_per_pair <= 0:
        raise ValueError("max_transitions_per_pair must be positive")

    primitives = lab_a_primitive_layers(angle_orders=angle_orders)
    locality = lab_a_wall_locality_constraint()
    yielded_pairs = 0
    yielded_candidates = 0
    for left, right in product(primitives, repeat=2):
        if left.name == right.name:
            continue
        if not spectrum_matches(left.matrix, right.matrix):
            continue
        yielded_pairs += 1
        if max_pairs is not None and yielded_pairs > max_pairs:
            return

        transitions, tier = solve_t_intertwiner_orthogonal(
            left.matrix,
            right.matrix,
            locality_constraint=locality,
            include_generic=include_generic,
        )
        for transition_index, transition in enumerate(transitions[:max_transitions_per_pair]):
            transition_name = (
                f"lab_a_wall_T_{transition_index}_{tier}_{left.name}_to_{right.name}"
            )
            layers = (
                left,
                right,
                _transition_layer(name=transition_name, matrix=transition),
            )
            name = f"lab_a_wall_{left.name}__to__{right.name}__T{transition_index}_{tier}"
            yield LabAWallCandidate(
                name=name,
                layers=layers,
                left_name=left.name,
                right_name=right.name,
                transition_tier=tier,
                transition_index=transition_index,
            )
            yielded_candidates += 1
            if max_candidates is not None and yielded_candidates >= max_candidates:
                return
