"""Phase 0a: bimultiplication-of-octonion triage.

The Furey-style "bimultiplication" candidate combines left- and right-
multiplications on T = C ⊗ H ⊗ O.  Restricted to the octonion factor,
the bimultiplication algebra Bi(O) = ⟨L_a, R_a⟩ closed under commutator
is a 28-dimensional Lie algebra, classically known to be Spin(8) via
the triality theorem.

The triality sidecar (``../triality/``) already showed that Spin(8)
triality fails the K1 test on the natural Pati-Salam-aligned SM Cartan
embedding.  This module computationally confirms that the
bimultiplication candidate collapses to that same Spin(8), and therefore
inherits the triality K1 fail.

Result: BIMULT KILL — confirms triality.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache

import sympy as sp

from clifford_3plus2_d5.exceptional.reuse import (
    octonion_left_multiplication,
    octonion_right_multiplication,
)


@lru_cache(maxsize=1)
def left_multiplications() -> tuple[sp.Matrix, ...]:
    """Return ``L_{e_1}, ..., L_{e_7}`` as 8×8 SymPy matrices."""

    return tuple(octonion_left_multiplication(index) for index in range(1, 8))


@lru_cache(maxsize=1)
def right_multiplications() -> tuple[sp.Matrix, ...]:
    """Return ``R_{e_1}, ..., R_{e_7}`` as 8×8 SymPy matrices."""

    return tuple(octonion_right_multiplication(index) for index in range(1, 8))


def _commutator(left: sp.Matrix, right: sp.Matrix) -> sp.Matrix:
    return (left * right - right * left).applyfunc(sp.simplify)


def bimultiplication_generators() -> tuple[sp.Matrix, ...]:
    """Return ``L_{e_i}`` and ``R_{e_i}`` and all pairwise commutators.

    For ``Bi(O)``, this single pass saturates the Lie algebra so(8).
    """

    L = left_multiplications()
    R = right_multiplications()
    result: list[sp.Matrix] = list(L) + list(R)
    # Add all distinct pairwise commutators.
    for index_i, item_i in enumerate(L):
        for index_j in range(index_i + 1, len(L)):
            result.append(_commutator(item_i, L[index_j]))
        for item_j in R:
            result.append(_commutator(item_i, item_j))
    for index_i, item_i in enumerate(R):
        for index_j in range(index_i + 1, len(R)):
            result.append(_commutator(item_i, R[index_j]))
    return tuple(result)


def _flatten(matrix: sp.Matrix) -> list[sp.Expr]:
    return [matrix[row, col] for row in range(matrix.rows) for col in range(matrix.cols)]


def bimultiplication_dimension() -> int:
    """Return the dimension of ``Bi(O)`` as a real Lie subalgebra of gl(8)."""

    matrices = bimultiplication_generators()
    return sp.Matrix([_flatten(matrix) for matrix in matrices]).T.rank()


def all_generators_skew_symmetric() -> bool:
    L = left_multiplications()
    R = right_multiplications()
    for matrix in (*L, *R):
        if (matrix + matrix.T).applyfunc(sp.simplify) != sp.zeros(matrix.rows, matrix.cols):
            return False
    return True


@dataclass(frozen=True)
class BimultiplicationAuditPayload:
    span_dimension: int
    so8_dimension: int
    matches_so8: bool
    all_skew_symmetric: bool
    triality_fail_reference: str
    verdict: str
    interpretation: str


def bimultiplication_audit_payload() -> BimultiplicationAuditPayload:
    """Run the Phase 0a triage."""

    dimension = bimultiplication_dimension()
    so8_dim = 28
    skew = all_generators_skew_symmetric()

    if dimension == so8_dim and skew:
        verdict = "BIMULT KILL — confirms triality"
        interpretation = (
            "The bimultiplication algebra Bi(O) generated by left- and "
            "right-multiplications on the octonions closes to a "
            "28-dimensional Lie subalgebra of gl(8), matching so(8) = "
            "Lie algebra of Spin(8).  This collapses the Furey "
            "bimultiplication candidate to the same Spin(8) whose triality "
            "fails K1 in ../triality/SESSION_T_KILL_TEST.md.  The "
            "bimultiplication-of-T approach to three generations is closed."
        )
    else:
        verdict = "BIMULT ANOMALY"
        interpretation = (
            f"Bi(O) has dimension {dimension} (expected 28).  Skew-symmetric "
            f"generators: {skew}.  Either implementation bug or genuinely "
            f"non-Spin(8) structure — investigate before drawing conclusions."
        )

    return BimultiplicationAuditPayload(
        span_dimension=dimension,
        so8_dimension=so8_dim,
        matches_so8=(dimension == so8_dim),
        all_skew_symmetric=skew,
        triality_fail_reference="../triality/SESSION_T_KILL_TEST.md",
        verdict=verdict,
        interpretation=interpretation,
    )
