"""Explicit Spin(8) inside the Cl(0,10) chiral-16 carrier, plus triality.

Per ``PLAN.md`` the pinned ``Spin(8) ⊂ Spin(10)`` embedding is the bivector
subalgebra generated by Cl(0,10) gamma indices ``{0..7}``.  All 28
generators ``(1/2) γ_i γ_j`` (``i < j < 8``) are constructed as 32x32 matrices
on the real-32 chiral-16 carrier using
``patisalam_chiral16_block_matrix``.

Cartan basis: ``H_k = (1/2) γ_{2k} γ_{2k+1}`` for ``k = 0, 1, 2, 3``.  These
four bivectors mutually commute and span a rank-4 Cartan subalgebra of
``so(8)``.

Triality is constructed via its action on this Cartan.  The 4x4 Cartan
matrix ``T_cartan`` was derived in ``PLAN.md`` from the requirement that
triality permute the three outer Dynkin nodes ``(α_1, α_3, α_4)`` while
fixing the central node ``α_2``.  The result is an orthogonal matrix of
order 3.

The full extension of triality to all 28 generators is not constructed
here.  The kill test ``sm_restriction.py`` only needs the Cartan action,
because the load-bearing question is whether the SM Cartan
``Cartan(SU(3)_c) ⊕ U(1)_{Y'}`` is preserved as a 3-dimensional subspace
of the 4-dimensional ``so(8)`` Cartan under ``T_cartan``.  If that fails,
``τ`` cannot preserve the SM subalgebra at the full level either.
"""

from __future__ import annotations

from functools import lru_cache
from itertools import combinations
from typing import TypeAlias

import sympy as sp

from clifford_3plus2_d5.triality.reuse import (
    patisalam_chiral16_block_matrix,
    patisalam_cl010_gamma_matrices,
)

MatrixTuple: TypeAlias = tuple[sp.Matrix, ...]


def spin8_bivector_indices() -> tuple[tuple[int, int], ...]:
    """Return the 28 unordered pairs ``(i, j)`` with ``0 <= i < j < 8``."""

    return tuple(combinations(range(8), 2))


def _spin8_bivector_full(first: int, second: int) -> sp.Matrix:
    if not (0 <= first < second < 8):
        raise ValueError("Spin(8) bivector indices must satisfy 0 <= i < j < 8")
    gammas = patisalam_cl010_gamma_matrices()
    return (sp.Rational(1, 2) * gammas[first] * gammas[second]).applyfunc(sp.simplify)


def spin8_generator_on_chiral16(first: int, second: int) -> sp.Matrix:
    """Return ``(1/2) γ_i γ_j`` restricted to the chiral-16 (32x32)."""

    full = _spin8_bivector_full(first, second)
    block = patisalam_chiral16_block_matrix(full)
    if block is None:
        raise RuntimeError(
            f"Spin(8) generator ({first},{second}) did not preserve chiral16",
        )
    return block


@lru_cache(maxsize=1)
def spin8_generators_on_chiral16() -> MatrixTuple:
    """Return all 28 Spin(8) generators on the chiral-16 carrier."""

    return tuple(
        spin8_generator_on_chiral16(first, second)
        for first, second in spin8_bivector_indices()
    )


def spin8_cartan_pairs() -> tuple[tuple[int, int], ...]:
    """Return the four bivector pairs defining the Cartan basis."""

    return ((0, 1), (2, 3), (4, 5), (6, 7))


@lru_cache(maxsize=1)
def spin8_cartan_on_chiral16() -> MatrixTuple:
    """Return ``H_0, H_1, H_2, H_3`` as 32x32 chiral-16 matrices."""

    return tuple(
        spin8_generator_on_chiral16(first, second)
        for first, second in spin8_cartan_pairs()
    )


def spin8_cartan_mutually_commute() -> bool:
    cartan = spin8_cartan_on_chiral16()
    zero = sp.zeros(cartan[0].rows)
    for left_index, left in enumerate(cartan):
        for right in cartan[:left_index]:
            commutator = (left * right - right * left).applyfunc(sp.simplify)
            if commutator != zero:
                return False
    return True


def triality_cartan_matrix() -> sp.Matrix:
    """Return the 4x4 Cartan matrix ``T_cartan`` of the triality automorphism.

    Derivation (from ``PLAN.md``):  triality cyclically permutes the three
    outer Dynkin nodes of D_4:

    .. code-block:: text

        α_1 = e_0 - e_1   →   α_3 = e_2 - e_3
        α_3 = e_2 - e_3   →   α_4 = e_2 + e_3
        α_4 = e_2 + e_3   →   α_1 = e_0 - e_1
        α_2 = e_1 - e_2   (fixed)

    Solving for the linear map ``T`` on ``span(e_0, e_1, e_2, e_3)`` gives
    the matrix below.  ``T`` is orthogonal and has order 3.
    """

    matrix = sp.Matrix(
        [
            [1, 1, 1, 1],
            [1, 1, -1, -1],
            [1, -1, 1, -1],
            [-1, 1, 1, -1],
        ],
    ) * sp.Rational(1, 2)
    return matrix.applyfunc(sp.simplify)


def triality_cartan_is_orthogonal() -> bool:
    matrix = triality_cartan_matrix()
    return (matrix.T * matrix - sp.eye(4)).applyfunc(sp.simplify) == sp.zeros(4)


def triality_cartan_is_order_three() -> bool:
    matrix = triality_cartan_matrix()
    cubed = (matrix * matrix * matrix).applyfunc(sp.simplify)
    return (cubed - sp.eye(4)).applyfunc(sp.simplify) == sp.zeros(4)


def triality_cartan_is_not_identity() -> bool:
    matrix = triality_cartan_matrix()
    return (matrix - sp.eye(4)).applyfunc(sp.simplify) != sp.zeros(4)


def triality_cartan_fixes_only_diagonal() -> int:
    """Return the dimension of the +1 eigenspace of ``T_cartan``.

    A non-identity order-3 orthogonal map on R^4 has a one-dimensional
    fixed subspace (the trace is ``1 + 2 cos(2 pi / 3) = 0`` would be the
    pure-cycle case; here the eigenvalues are ``1, 1, ω, ω̄`` so the
    fixed subspace is 2-dimensional).
    """

    matrix = triality_cartan_matrix()
    return (matrix - sp.eye(4)).nullspace().__len__()


def apply_triality_to_cartan_vector(coefficients: sp.Matrix) -> sp.Matrix:
    """Apply ``T_cartan`` to a Cartan vector expressed in the ``H_k`` basis.

    The input is a 4x1 column ``(c_0, c_1, c_2, c_3)`` representing
    ``c_0 H_0 + c_1 H_1 + c_2 H_2 + c_3 H_3``.  The output is the same
    column-vector representation of the triality image.
    """

    if coefficients.shape != (4, 1):
        raise ValueError("Cartan vector must be a 4x1 column")
    return (triality_cartan_matrix() * coefficients).applyfunc(sp.simplify)


def _flatten_to_column(matrix: sp.Matrix) -> sp.Matrix:
    entries = [matrix[row, col] for row in range(matrix.rows) for col in range(matrix.cols)]
    return sp.Matrix(matrix.rows * matrix.cols, 1, entries)


def cartan_coordinates(matrix: sp.Matrix) -> sp.Matrix | None:
    """Express ``matrix`` as a linear combination of ``H_0..H_3``.

    Returns the 4x1 coefficient column if ``matrix`` is in the Cartan span,
    otherwise ``None``.
    """

    if matrix.shape != (32, 32):
        return None
    cartan = spin8_cartan_on_chiral16()
    basis = sp.Matrix.hstack(*(_flatten_to_column(item) for item in cartan))
    target = _flatten_to_column(matrix)
    solution = basis.solve_least_squares(target)
    residual = (basis * solution - target).applyfunc(sp.simplify)
    if residual != sp.zeros(target.rows, 1):
        return None
    return solution.applyfunc(sp.simplify)


def is_in_cartan_span(matrix: sp.Matrix) -> bool:
    return cartan_coordinates(matrix) is not None
