"""V5 nilpotent boundary-flag origin for the path repair scar.

V1-V4 treat the path scar as an effective repair graph.  V5 asks whether the
same path operator can be generated by a more algebraic boundary defect: a
length-3 nilpotent flag

    b -> a -> u.

With port order ``(u, a, b)``, the canonical repair monodromy is

    N = |u><a| + |a><b|.

The Hermitian graph data are recovered from the nilpotent:

    A_flag = N + N.T,
    D_flag = N N.T + N.T N,
    Delta_flag = D_flag - A_flag.

For the canonical equal unit flag, ``Delta_flag = Delta(P3)``.  This upgrades
the path scar from an edge-weight minimum to a nilpotent repair-flag origin,
while still leaving the microscopic origin of the flag itself open.
"""

from __future__ import annotations

from dataclasses import dataclass

import sympy as sp

from clifford_3plus2_d5.depth_scar.repair_graphs import (
    EXPECTED_DEPTH_SPECTRUM,
    EXPECTED_LAPLACIAN_SPECTRUM,
    defect_eigenbasis_matrix,
    k3_laplacian,
    path_laplacian,
    transfer_operator_eigenbasis,
    transfer_operator_port_basis,
)


def _sorted_eigenvalues(matrix: sp.Matrix) -> tuple[sp.Expr, ...]:
    """Return exact eigenvalues with multiplicity in deterministic order."""

    values: list[sp.Expr] = []
    for eigenvalue, multiplicity in matrix.eigenvals().items():
        values.extend([sp.simplify(eigenvalue)] * multiplicity)
    return tuple(sorted(values, key=sp.default_sort_key))


def nilpotent_flag_operator() -> sp.Matrix:
    """Return the canonical length-3 repair flag ``N = |u><a| + |a><b|``."""

    return sp.Matrix(
        [
            [0, 1, 0],
            [0, 0, 1],
            [0, 0, 0],
        ]
    )


def weighted_nilpotent_flag_operator(x: sp.Expr, y: sp.Expr) -> sp.Matrix:
    """Return ``N(x,y) = x|u><a| + y|a><b|``."""

    return sp.Matrix(
        [
            [0, x, 0],
            [0, 0, y],
            [0, 0, 0],
        ]
    )


def nilpotent_order_pass(operator: sp.Matrix | None = None) -> bool:
    """Return whether the operator is a genuine length-3 nilpotent."""

    if operator is None:
        operator = nilpotent_flag_operator()
    return (
        sp.simplify(operator**3) == sp.zeros(3, 3)
        and sp.simplify(operator**2) != sp.zeros(3, 3)
    )


def flag_adjacency_operator(operator: sp.Matrix | None = None) -> sp.Matrix:
    """Return the undirected repair adjacency induced by the nilpotent flag."""

    if operator is None:
        operator = nilpotent_flag_operator()
    return sp.simplify(operator + operator.T)


def flag_degree_operator(operator: sp.Matrix | None = None) -> sp.Matrix:
    """Return the repair degree operator induced by the nilpotent flag."""

    if operator is None:
        operator = nilpotent_flag_operator()
    return sp.simplify(operator * operator.T + operator.T * operator)


def flag_laplacian_from_nilpotent(operator: sp.Matrix | None = None) -> sp.Matrix:
    """Return ``Delta_flag = D_flag - A_flag``."""

    if operator is None:
        operator = nilpotent_flag_operator()
    return sp.simplify(flag_degree_operator(operator) - flag_adjacency_operator(operator))


def nilpotent_flag_laplacian_matches_path() -> bool:
    """Return whether the canonical flag recovers ``Delta(P3)`` exactly."""

    return sp.simplify(flag_laplacian_from_nilpotent() - path_laplacian()) == sp.zeros(3, 3)


def nilpotent_flag_spectrum_pass() -> bool:
    """Return whether the canonical flag gives the target spectra."""

    laplacian = flag_laplacian_from_nilpotent()
    return (
        _sorted_eigenvalues(laplacian) == EXPECTED_LAPLACIAN_SPECTRUM
        and _sorted_eigenvalues(2 * laplacian) == EXPECTED_DEPTH_SPECTRUM
    )


def nilpotent_flag_transfer_operator() -> sp.Matrix:
    """Return the transfer operator induced by the nilpotent-flag Laplacian."""

    basis = defect_eigenbasis_matrix()
    return sp.simplify(basis * transfer_operator_eigenbasis() * basis.T)


def nilpotent_flag_transfer_matches_v1() -> bool:
    """Return whether the nilpotent flag reproduces the V1 transfer kernel."""

    return sp.simplify(nilpotent_flag_transfer_operator() - transfer_operator_port_basis()) == sp.zeros(
        3, 3
    )


def rank_one_nilpotent_control_operator() -> sp.Matrix:
    """Return a shorter nilpotent that does not encode a length-3 flag."""

    return sp.Matrix(
        [
            [0, 1, 0],
            [0, 0, 0],
            [0, 0, 0],
        ]
    )


def rank_one_nilpotent_control_rejected() -> bool:
    """Return whether the rank-one control misses the target spectrum."""

    control = rank_one_nilpotent_control_operator()
    return (
        sp.simplify(control**2) == sp.zeros(3, 3)
        and _sorted_eigenvalues(flag_laplacian_from_nilpotent(control))
        != EXPECTED_LAPLACIAN_SPECTRUM
    )


def cyclic_closure_control_rejected() -> bool:
    """Return whether closing the repair cycle gives the degenerate ``K3`` control."""

    return (
        _sorted_eigenvalues(k3_laplacian()) == (sp.Integer(0), sp.Integer(3), sp.Integer(3))
        and _sorted_eigenvalues(k3_laplacian()) != EXPECTED_LAPLACIAN_SPECTRUM
    )


def weighted_flag_target_solutions() -> tuple[tuple[sp.Expr, sp.Expr], ...]:
    """Return real weighted-flag amplitudes that preserve the target spectrum.

    The characteristic-polynomial constraints force ``x**2 = y**2 = 1``.
    On nonnegative amplitudes, this leaves only the canonical unit flag.
    """

    return (
        (-sp.Integer(1), -sp.Integer(1)),
        (-sp.Integer(1), sp.Integer(1)),
        (sp.Integer(1), -sp.Integer(1)),
        (sp.Integer(1), sp.Integer(1)),
    )


def nonnegative_weighted_flag_target_solution() -> tuple[sp.Expr, sp.Expr]:
    """Return the unique nonnegative weighted-flag target solution."""

    return sp.Integer(1), sp.Integer(1)


def weighted_flag_target_conditions_pass() -> bool:
    """Return whether the weighted target conditions force unit adjacent steps."""

    x, y, lam = sp.symbols("x y lambda")
    laplacian = flag_laplacian_from_nilpotent(weighted_nilpotent_flag_operator(x, y))
    target_charpoly = lam * (lam - 1) * (lam - 3)
    residual = sp.Poly(
        sp.expand(laplacian.charpoly(lam).as_expr() - target_charpoly),
        lam,
    )
    real_solutions = set(weighted_flag_target_solutions())
    solved = set(
        tuple(sp.simplify(solution[symbol]) for symbol in (x, y))
        for solution in sp.solve(residual.coeffs(), (x, y), dict=True)
    )
    return solved == real_solutions and nonnegative_weighted_flag_target_solution() == (
        sp.Integer(1),
        sp.Integer(1),
    )


def nilpotent_flag_controls_pass() -> bool:
    """Return whether the negative controls separate the canonical flag."""

    return (
        rank_one_nilpotent_control_rejected()
        and cyclic_closure_control_rejected()
        and weighted_flag_target_conditions_pass()
    )


@dataclass(frozen=True)
class NilpotentFlagScarPayload:
    """V5 payload for the nilpotent-flag scar-origin gate."""

    final_verdict: str
    nilpotent_order_pass: bool
    laplacian_matches_path: bool
    spectrum_pass: bool
    transfer_matches_v1: bool
    rank_one_control_rejected: bool
    cyclic_closure_control_rejected: bool
    weighted_target_conditions_pass: bool
    equal_unit_flag_steps_microscopically_derived: bool
    interpretation: str


def nilpotent_flag_scar_payload() -> NilpotentFlagScarPayload:
    """Return the V5 nilpotent-flag scar-origin verdict."""

    order_pass = nilpotent_order_pass()
    laplacian_matches = nilpotent_flag_laplacian_matches_path()
    spectrum_pass = nilpotent_flag_spectrum_pass()
    transfer_matches = nilpotent_flag_transfer_matches_v1()
    rank_one_control = rank_one_nilpotent_control_rejected()
    cyclic_control = cyclic_closure_control_rejected()
    weighted_conditions = weighted_flag_target_conditions_pass()

    checks_pass = (
        order_pass
        and laplacian_matches
        and spectrum_pass
        and transfer_matches
        and rank_one_control
        and cyclic_control
        and weighted_conditions
    )

    if checks_pass:
        final_verdict = "NILPOTENT_FLAG_SCAR_ORIGIN_PASS"
        interpretation = (
            "The canonical length-3 nilpotent repair flag N=|u><a|+|a><b| "
            "induces the path adjacency, path degree operator, and exactly "
            "Delta(P3). Its BCC-doubled spectrum is {0,2,6}, and the transfer "
            "kernel matches V1. The remaining input is the microscopic origin "
            "of the equal unit flag steps."
        )
    elif not order_pass:
        final_verdict = "NILPOTENT_FLAG_ORDER_KILL"
        interpretation = "The proposed repair operator is not a genuine length-3 nilpotent."
    elif not spectrum_pass:
        final_verdict = "NILPOTENT_FLAG_SPECTRUM_KILL"
        interpretation = "The induced nilpotent-flag Laplacian misses the target spectrum."
    else:
        final_verdict = "NILPOTENT_FLAG_CONTROL_KILL"
        interpretation = "A transfer, rank-one, cyclic, or weighted-control gate failed."

    return NilpotentFlagScarPayload(
        final_verdict=final_verdict,
        nilpotent_order_pass=order_pass,
        laplacian_matches_path=laplacian_matches,
        spectrum_pass=spectrum_pass,
        transfer_matches_v1=transfer_matches,
        rank_one_control_rejected=rank_one_control,
        cyclic_closure_control_rejected=cyclic_control,
        weighted_target_conditions_pass=weighted_conditions,
        equal_unit_flag_steps_microscopically_derived=False,
        interpretation=interpretation,
    )
