"""Small exact search for simple projectors generated by rule data."""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product
from typing import Literal

import sympy as sp

from clifford_3plus2_d5.algebra.commutants import matrix_span_rank
from clifford_3plus2_d5.algebra.matrices import commutator, identity, is_zero_matrix
from clifford_3plus2_d5.algebra.real_carrier import standard_real_carrier
from clifford_3plus2_d5.search.addressability import AddressableOperator


ProjectorDiscoveryVerdict = Literal["projector_pair_found", "not_found"]


@dataclass(frozen=True)
class ProjectorDiscoveryResult:
    candidate_count: int
    rank_6_projectors: int
    rank_4_projectors: int
    projector_pair_found: bool
    verdict: ProjectorDiscoveryVerdict


def _append_if_independent(basis: list[sp.Matrix], candidate: sp.Matrix) -> None:
    if not basis or matrix_span_rank([*basis, candidate]) > matrix_span_rank(basis):
        basis.append(candidate)


def _independent_basis(matrices: tuple[sp.Matrix, ...]) -> tuple[sp.Matrix, ...]:
    basis: list[sp.Matrix] = []
    for matrix in matrices:
        _append_if_independent(basis, matrix)
    return tuple(basis)


def discover_projector_pair(
    *,
    candidate_j: sp.Matrix | None = None,
    rule_data_operators: tuple[AddressableOperator, ...],
    coefficient_values: tuple[int, ...] = (-1, 0, 1),
    max_basis_size: int = 7,
) -> ProjectorDiscoveryResult:
    carrier = standard_real_carrier()
    candidate_j = candidate_j if candidate_j is not None else carrier.complex_structure
    basis = _independent_basis(
        (identity(carrier.dimension),)
        + tuple(operator.matrix for operator in rule_data_operators)
    )[:max_basis_size]

    projectors: list[sp.Matrix] = []
    for coefficients in product(coefficient_values, repeat=len(basis)):
        if all(coefficient == 0 for coefficient in coefficients):
            continue

        matrix = sp.zeros(carrier.dimension)
        for coefficient, basis_matrix in zip(coefficients, basis, strict=True):
            matrix += coefficient * basis_matrix

        if matrix * matrix != matrix:
            continue
        if not is_zero_matrix(commutator(matrix, candidate_j)):
            continue
        if matrix.rank() not in {4, 6}:
            continue
        if not any(matrix == projector for projector in projectors):
            projectors.append(matrix)

    rank_6 = tuple(projector for projector in projectors if projector.rank() == 6)
    rank_4 = tuple(projector for projector in projectors if projector.rank() == 4)
    pair_found = any(
        p6 + p4 == identity(carrier.dimension) and p6 * p4 == sp.zeros(carrier.dimension)
        for p6 in rank_6
        for p4 in rank_4
    )
    return ProjectorDiscoveryResult(
        candidate_count=len(projectors),
        rank_6_projectors=len(rank_6),
        rank_4_projectors=len(rank_4),
        projector_pair_found=pair_found,
        verdict="projector_pair_found" if pair_found else "not_found",
    )


def discovery_to_dict(result: ProjectorDiscoveryResult) -> dict[str, object]:
    return {
        "candidate_count": result.candidate_count,
        "rank_6_projectors": result.rank_6_projectors,
        "rank_4_projectors": result.rank_4_projectors,
        "projector_pair_found": result.projector_pair_found,
        "verdict": result.verdict,
    }
