"""Session 13 boundary-material origin audit.

Session 12 closes the neutrino family-port graph inside the
single-clock/outgoing-boundary model.  This module asks whether the remaining
physical premises are already forced by the bare BB edge data:

    1. the boundary realizes a positive single-clock locking field;
    2. mixed-normal clock-error ports are outgoing asymptotic leads.

The answer is deliberately negative.  Local edge kinematics forces the
reflection-odd mismatch coordinate ``q = r1-r2`` once a single edge clock is
assumed.  But the bare BB emission blocks contain no boundary-material energy
functional and no asymptotic "no incoming clock-error" condition.  Retarded and
recurrent completions use the same local mixed-normal emission blocks but give
different visible powers.  Therefore the outgoing/locking premise is not
derivable from the bare BB block algebra alone.
"""

from __future__ import annotations

from dataclasses import dataclass

import sympy as sp

from clifford_3plus2_d5.universal_bath.neutrino_bcc_moments import (
    bb_edge_blocks,
    mixed_normal_norm,
    same_normal_norm,
)
from clifford_3plus2_d5.universal_bath.neutrino_family_port_graph import matrix_equal
from clifford_3plus2_d5.universal_bath.neutrino_q_mismatch_retarded import (
    q_mismatch_retarded_payload,
    recurrent_two_step_return,
    recurrent_visible_powers_differ,
    retarded_visible_powers_match_survival,
)


@dataclass(frozen=True)
class BoundaryMaterialAuditPayload:
    """Session 13 verdict for the remaining boundary-material premise."""

    final_verdict: str
    local_mismatch_coordinate_unique: bool
    positive_penalty_if_constraint_admitted: bool
    bare_blocks_have_no_gap_parameter: bool
    retarded_completion_uses_same_emission_norm: bool
    recurrent_completion_uses_same_emission_norm: bool
    retarded_and_recurrent_visible_powers_differ: bool
    recurrent_two_step_return_nonzero: bool
    outgoing_asymptotics_forced_by_bare_blocks: bool
    positive_locking_forced_by_bare_blocks: bool
    session_12_conditional_graph_passes: bool
    next_required_object: str
    interpretation: str


def local_linear_mismatch_solution_space() -> tuple[sp.Matrix, ...]:
    """Return a basis for linear forms vanishing on the synchronous line.

    A local linear mismatch built from two normal depths has the form
    ``K = a r1 + b r2``.  Requiring ``K(r,r)=0`` gives ``a+b=0``, so the solution
    space is one-dimensional and generated by ``r1-r2``.
    """

    return (sp.Matrix([1, -1]),)


def local_mismatch_coordinate_is_unique() -> bool:
    """Return whether the only local linear mismatch is proportional to q."""

    basis = local_linear_mismatch_solution_space()
    generator = basis[0]
    r = sp.symbols("r")
    synchronous_value = sp.simplify(generator.dot(sp.Matrix([r, r])))
    return len(basis) == 1 and synchronous_value == 0 and generator == sp.Matrix([1, -1])


def positive_penalty_if_constraint_admitted() -> bool:
    """Return whether ``K^T K`` gives the positive quadratic q penalty."""

    r1, r2 = sp.symbols("r1 r2", real=True)
    q = r1 - r2
    penalty = sp.expand(q**2)
    return penalty == sp.expand((sp.Matrix([[1, -1]]) * sp.Matrix([r1, r2]))[0] ** 2)


def bare_blocks_have_no_gap_parameter() -> bool:
    """Return true when exact BB blocks contain no stiffness/gap symbol."""

    blocks = bb_edge_blocks()
    entries = [*blocks.b_plus, *blocks.b_minus, *blocks.m_plus2, *blocks.m_minus2]
    forbidden = {sp.Symbol("g"), sp.Symbol("Lambda")}
    return all(entry.free_symbols.isdisjoint(forbidden) for entry in entries)


def emission_norm_is_same_for_retarded_and_recurrent() -> bool:
    """Return whether both completions start from the same BB emission norm."""

    same = same_normal_norm()
    mixed = mixed_normal_norm()
    return matrix_equal(same, sp.eye(2) / 2) and matrix_equal(mixed, sp.eye(2) / 2)


def outgoing_asymptotics_not_forced_by_bare_blocks() -> bool:
    """Return true when same local emission supports different completions."""

    retarded = retarded_visible_powers_match_survival(shells=4, powers=(0, 1, 2, 3))
    recurrent_differs = recurrent_visible_powers_differ(shells=4)
    recurrent_return = not matrix_equal(recurrent_two_step_return(), sp.zeros(2))
    return retarded and recurrent_differs and recurrent_return


def boundary_material_audit_payload() -> BoundaryMaterialAuditPayload:
    """Return the Session 13 boundary-material origin audit."""

    unique = local_mismatch_coordinate_is_unique()
    positive = positive_penalty_if_constraint_admitted()
    no_gap = bare_blocks_have_no_gap_parameter()
    same_emission = emission_norm_is_same_for_retarded_and_recurrent()
    asymptotics_not_forced = outgoing_asymptotics_not_forced_by_bare_blocks()
    session_12 = q_mismatch_retarded_payload()
    session_12_pass = (
        session_12.final_verdict == "NEUTRINO_Q_MISMATCH_RETARDED_COMPRESSION_PASS"
    )

    outgoing_forced = False
    locking_forced = False
    recurrent_return_nonzero = not matrix_equal(recurrent_two_step_return(), sp.zeros(2))
    powers_differ = recurrent_visible_powers_differ(shells=4)

    checks_pass = (
        unique
        and positive
        and no_gap
        and same_emission
        and asymptotics_not_forced
        and recurrent_return_nonzero
        and powers_differ
        and session_12_pass
        and not outgoing_forced
        and not locking_forced
    )

    if checks_pass:
        final_verdict = "NEUTRINO_BOUNDARY_MATERIAL_ORIGIN_NOT_DERIVED_AUDIT"
        interpretation = (
            "The local two-face geometry uniquely identifies q=r1-r2 as the "
            "linear single-clock mismatch, and K^T K gives a positive q^2 "
            "penalty if that constraint field is admitted.  However, the bare "
            "BB blocks contain no stiffness/gap parameter and no asymptotic "
            "condition.  Retarded and recurrent completions start from the "
            "same local mixed-normal emission norm, but the recurrent wedge "
            "has nonzero two-step return and changes visible powers.  Thus "
            "Session 12 is a valid conditional microscopic graph inside the "
            "single-clock/outgoing model, but the deeper boundary-material "
            "origin of that model is not derived from bare BB block algebra."
        )
    else:
        final_verdict = "NEUTRINO_BOUNDARY_MATERIAL_AUDIT_KILL"
        interpretation = (
            "The mismatch uniqueness, positive-penalty implication, absence of "
            "a bare gap parameter, retarded/recurrent discrimination, or "
            "Session 12 prerequisite failed."
        )

    return BoundaryMaterialAuditPayload(
        final_verdict=final_verdict,
        local_mismatch_coordinate_unique=unique,
        positive_penalty_if_constraint_admitted=positive,
        bare_blocks_have_no_gap_parameter=no_gap,
        retarded_completion_uses_same_emission_norm=same_emission,
        recurrent_completion_uses_same_emission_norm=same_emission,
        retarded_and_recurrent_visible_powers_differ=powers_differ,
        recurrent_two_step_return_nonzero=recurrent_return_nonzero,
        outgoing_asymptotics_forced_by_bare_blocks=outgoing_forced,
        positive_locking_forced_by_bare_blocks=locking_forced,
        session_12_conditional_graph_passes=session_12_pass,
        next_required_object=(
            "boundary-material model deriving positive single-clock locking "
            "and outgoing clock-error asymptotics"
        ),
        interpretation=interpretation,
    )
